### ISSUE TITLE
Error on `npm run dev`

### ISSUE THREAD

**Issue by jgarrow** [Girish21/speed-metal-stack#4]
Hello! 👋

I'm doing an initial setup using speed-metal-stack and am running into an error.

## Steps to reproduce

1. Run `npx create-remix --template Girish21/speed-metal-stack`
2. cd into newly created directory and run `npm run setup`
3. Run `npm run build`
4. Run `npm run dev` and get the error below (It doesn't seem to like any of the `~/` imports?):

```bash
> dev
> run-p dev:*


> dev:server
> cross-env NODE_ENV=development node --inspect --require dotenv/config --require ./mocks ./build/server.js


> dev:build
> cross-env NODE_ENV=development npm run build:server -- --watch


> dev:css
> tailwindcss -w -i styles/app.css -o app/styles/app.css


> dev:content
> node -r esbuild-register -r dotenv/config others/refresh-on-content-change.ts


> dev:remix
> cross-env NODE_ENV=development remix watch

Debugger listening on ws://127.0.0.1:9229/15a1f155-0c16-4ad3-a794-dc8fed5de229
For help, see: https://nodejs.org/en/docs/inspector
MSW initialised

Rebuilding...

> build:server
> esbuild --platform=node --format=cjs ./server/index.ts --outfile=build/server.js "--watch"

[watch] build finished, watching for changes...
(node:32298) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Cannot find module '~/components/nav'
Require stack:
- /Users/janessa/Dev/remix/mdx-stack/build/index.js
- /Users/janessa/Dev/remix/mdx-stack/build/server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/janessa/Dev/remix/mdx-stack/build/index.js:98:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/janessa/Dev/remix/mdx-stack/node_modules/esbuild-register/dist/node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader (/Users/janessa/Dev/remix/mdx-stack/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.extensions..js (/Users/janessa/Dev/remix/mdx-stack/node_modules/esbuild-register/dist/node.js:4801:24)
ERROR: "dev:server" exited with 1.
```

## Environment

- Node v16.13.2
- npm v8.1.2
- MacOS

Any ideas what might be happening?

**Comment by bmeverett** [comment]
I am also having the same issue. I've tried creating a template as well as pulling this repo and trying within this repo and get the same issue.

**Comment by Girish21** [comment]
@jgarrow @bmeverett 👋

Remix added the ability to add a custom path alias other than the default `~` here [#2412](https://github.com/remix-run/remix/pull/2412); this broke the ability to have a different `tsconfig` for each directory in the project. Since now `@remix-run/dev` reads the `tsconfig` at the root of the project for the path alias, the existing setup will not work, and I pushed the fix to use the common `tsconfig` at the root of the project for all the directories.

Please run `npx create-remix@latest --template Girish21/speed-metal-stack` to create a new project with the updated project structure for Remix versions `>1.3.4`

**Comment by bmeverett** [comment]
@Girish21 Thank you for the response and quick fix! That did the trick!

**Comment by jgarrow** [comment]
Thanks @Girish21! That worked like a charm 😊
