### ISSUE TITLE
New Deploy for each new blog post

### ISSUE THREAD

**Issue by niklasgrewe** [Girish21/speed-metal-stack#6]
Hi, thank you very much for this awesome starter stack. I played a little bit with it and i notice, that the Github Action `Deploy` doesn't exit, even when i only change the content under `content/blog`. I checked the logs under ⚙️ Determine Changes

```
Run echo ::set-output name=DEPLOYABLE::$(node ./others/is-deployable.js)
  echo ::set-output name=DEPLOYABLE::$(node ./others/is-deployable.js)
  shell: /usr/bin/bash -e {0}
  env:
    FLY_APP_NAME: ***
TypeError: Cannot read properties of undefined (reading 'sha')
    at go (/home/runner/work/blog/blog/others/is-deployable.js:7:[3](https://github.com/:repo/blog/runs/6241374380?check_suite_focus=true#step:5:3)0)
    at processTicksAndRejections (node:internal/process/task_queues:96:[5](https://github.com/:repo/blog/runs/6241374380?check_suite_focus=true#step:5:5))
```
I follow the readme for Deployment and setup the following Github Actions Secret
```
FLY_API_TOKEN=*****
FLY_APP_NAME=*****
REFRESH_TOKEN=*****
```
I also checked the `buildInfo` endpoint. When i manuell go to `https://{app}.fly.dev/build/info.json` i only receive this values:
```
{
  "timestamp": 1651339488348
}
```
So sha is not defined and so `isDeployable` is always `true`

Have I forgotten anything or done anything wrong? Interestingly, despite the new deployment, the new posts do not show up in the blog list under `/blog` unless I go manuell to the appropriate slug like `/blog/hello-world`.

**Comment by Girish21** [comment]
> Github Action Deploy doesn't exit
Can you elaborate, please?

> TypeError: Cannot read properties of undefined (reading 'sha')
can you recheck the `FLY_APP_NAME` secret? It should be the app name present in the [fly.toml](https://github.com/Girish21/test-speed-metal/blob/main/fly.toml#L3) file

**Comment by Girish21** [comment]
and did you run your first deployment from local instead of GitHub?

**Comment by niklasgrewe** [comment]
> Can you elaborate, please?

I mean that the page is redeployed instead of just updating the content 

> can you recheck the FLY_APP_NAME secret?

yes the name is identical with the app name in `fly.toml`

> and did you run your first deployment from local instead of GitHub?

no i start the deployment process with this comand, coming from readme

```
flyctl launch --name YOUR_APP_NAME --copy-config --no-deploy
```

I think i found the error. I compare your buildInfo with mine. The result:

your buildInfo
```
{
  "timestamp": 1651339974568,
  "data": {
    "author": "Girish21",
    "timestamp": "2022-04-30T17:28:04Z",
    "sha": "7c750187be9eecb3624fd05b6b282cd7b132fbb0",
    "message": "init 🚀",
    "url": "https://github.com/Girish21/test-speed-metal/commit/7c750187be9eecb3624fd05b6b282cd7b132fbb0"
  }
}
```
my buildInfo
```
{
  "timestamp": 1651339488348
}
```
can you explain why these values are missing for me, even though I used Github Actions to deploy?

**Comment by niklasgrewe** [comment]
could you maybe tell me exactly the steps you took?

**Comment by Girish21** [comment]
> I completely forgot to adjust the .env.example file. Could this be related to that?

No, the repo name will be passed as an environment variable when the GitHub actions si invoked https://github.com/Girish21/speed-metal-stack/blob/main/.github/workflows/deploy.yml#L194

Can you check the `build` step logs and see if any errors are thrown?

> could you maybe tell me precisely the steps you took?

I followed the exact steps described in the Readme

**Comment by niklasgrewe** [comment]
@Girish21 i created a brand new project + repo and it works now, without any problems. The only thing i changed was the permissions of the Github Access Token. Additional to all repo permissions, i also checked the workflow permission. Could this be related?

Regardless, it might be good if you explained in the readme what permissions you need to set for the access token. A screenshot might be helpful here, especially for still junior developers like me 😄

**Comment by Girish21** [comment]
> The only thing i changed was the permissions of the Github Access Token. Additional to all repo permissions, i also checked the workflow permission. Could this be related?

AFAIK, we don't need permissions other than to pull files under the `content` directory from the app. And I think something got misconfigured the first time around?

> What are these needed for in dev mode?

Only `DATABASE_URL` and `SESSION_SECRETS` will be used during local development. We won't make calls to GitHub during local development, and all requests to GitHub APIs from local are [mocked](https://github.com/Girish21/speed-metal-stack/blob/main/package.json#L13) using [MSW](https://mswjs.io/). You can find the mocks [here](https://github.com/Girish21/speed-metal-stack/tree/main/mocks).

**Comment by niklasgrewe** [comment]
thank you for the clarification. Now that everything is working as expected, I will close this case. Thanks again for your patience and your answers 👍
